Repository opencloud-eu/helm, pull requests merged in 2025-06, with the labels that each got.

#61 README.md: remove actual installation steps, as those are describe in each chart's README.md
  README.md
Labels: Type:Documentation, Status:Needs-Review

#76 Fix inconsistent rendering of booleans
  charts/opencloud/Chart.yaml
  charts/opencloud/templates/collaboration/deployment.yaml
  charts/opencloud/templates/onlyoffice/deployment.yaml
  charts/opencloud/templates/opencloud/deployment.yaml
Labels: Type:Enhancement, Status:Needs-Review, Status:Completed

#56 charts/opencloud/README.md: add global.domain.wopi
  charts/opencloud/README.md
Labels: Type:Bug, Type:Documentation, Status:Needs-Review

#66 charts/opencloud/README.md: remove duplicate clusterIssuer
  charts/opencloud/README.md
Labels: Type:Bug, Type:Documentation, Status:Needs-Review

#81 [opencloud] remove YAML code for Gateway from README.md, adapt helm install command to do the needful
  charts/opencloud/README.md
Labels: Type:Enhancement, Type:Documentation, Status:Needs-Review

#83 Add kastl-ars and Tim-herbie as reviewers
  MAINTAINERS.md
Labels: Type:Organizational, Status:Proposal, Status:Completed

#62 charts/opencloud/values.yaml: do not set the cert-manager annotation by default
  charts/opencloud/values.yaml
Labels: Type:Enhancement, Type:Breaking-Change, Status:Needs-Review, Status:Completed

#84 feat: implement external Keycloak support (fixes #75, #82)
  charts/opencloud/Chart.yaml
  charts/opencloud/README.md
  charts/opencloud/templates/gateway/keycloak-https-httproute.yaml
  charts/opencloud/templates/keycloak/deployment.yaml
  charts/opencloud/templates/keycloak/ingress.yaml
  charts/opencloud/templates/keycloak/realm-configmap.yaml
  charts/opencloud/templates/keycloak/script-configmap.yaml
  charts/opencloud/templates/keycloak/service.yaml
  charts/opencloud/templates/opencloud/deployment.yaml
  charts/opencloud/templates/postgres/deployment.yaml
  charts/opencloud/templates/postgres/pvc.yaml
  charts/opencloud/templates/postgres/service.yaml
  charts/opencloud/values.yaml
Labels: Type:Bug, Type:Feature, Type:Breaking-Change, Status:Proposal

#91 fix annotation preset
  charts/opencloud/templates/onlyoffice/ingress.yaml
Labels: Type:Bug

#63 Add support for existing secrets and replace plaintext values with secrets
  charts/opencloud/Chart.yaml
  charts/opencloud/README.md
  charts/opencloud/files/onlyoffice/local.json.gotmpl
  charts/opencloud/templates/NOTES.txt
  charts/opencloud/templates/collabora/deployment.yaml
  charts/opencloud/templates/collabora/secrets.yaml
  charts/opencloud/templates/gateway/gateway.yaml
  charts/opencloud/templates/keycloak/deployment.yaml
  charts/opencloud/templates/keycloak/secrets.yaml
  charts/opencloud/templates/minio/deployment.yaml
  charts/opencloud/templates/minio/secrets.yaml
  charts/opencloud/templates/onlyoffice/deployment.yaml
  charts/opencloud/templates/onlyoffice/secrets.yaml
  charts/opencloud/templates/opencloud/deployment.yaml
  charts/opencloud/templates/opencloud/secrets.yaml
  charts/opencloud/templates/postgres/deployment.yaml
  charts/opencloud/templates/postgres/secrets.yaml
  charts/opencloud/values.yaml
Labels: Type:Feature, Type:Security, Status:In-Progress
